class program
{
    public static void Main(string[] args)
    {
        Soldiers soldier1 = new Soldiers(1, "Arthur", 100, 1, 2, 3, 10, "arrows", "iron", 50, 10, "archer", 5, 1, 5);
        Soldiers soldier2 = new Soldiers(2, "Lancelot", 90, -1, 2, -3, 15, "swords", "silver", 100, 5, "knight", 7, 2, 10);
        Soldiers soldier3 = new Soldiers(3, "Gawain", 110, 0, 0, 0, 20, "arrows", "iron", 75, 8, "archer", 6, 3, 8);
        Soldiers soldier4 = new Soldiers(4, "Galahad", 95, 2, -2, 1, 12, "arrows", "iron", 60, 9, "archer", 8, 4, 6);
        Soldiers soldier5 = new Soldiers(5, "Percival", 105, -2, 3, -1, 18, "swords", "silver", 120, 4, "knight", 9, 5, 12);
        Soldiers soldier6 = new Soldiers(6, "Tristan", 98, 1, 3, 1, 25, "arrows", "iron", 80, 10, "archer", 10, 6, 10);
        Soldiers soldier7 = new Soldiers(7, "Mordred", 87, -3, -2, 2, 30, "swords", "silver", 90, 3, "knight", 6, 7, 14);
        Soldiers soldier8 = new Soldiers(8, "Kay", 93, 2, 2, -2, 14, "arrows", "iron", 55, 7, "archer", 7, 8, 7);
        Soldiers soldier9 = new Soldiers(9, "Bedivere", 110, 0, 2, 3, 10, "swords", "silver", 110, 6, "knight", 5, 9, 11);
        Soldiers soldier10 = new Soldiers(10, "Bors", 99, -1, 1, 2, 22, "arrows", "iron", 95, 9, "archer", 7, 10, 9);
        Soldiers soldier11 = new Soldiers(11, "Dagonet", 85, 1, -3, -2, 16, "swords", "silver", 85, 8, "knight", 6, 11, 10);
        Soldiers soldier12 = new Soldiers(12, "Agravain", 101, 3, 0, 3, 10, "arrows", "iron", 60, 4, "archer", 8, 12, 5);
        Soldiers soldier13 = new Soldiers(13, "Lamorak", 96, -2, -1, 1, 19, "swords", "silver", 105, 7, "knight", 9, 13, 11);
        Soldiers soldier14 = new Soldiers(14, "Gareth", 89, 0, 3, -1, 27, "arrows", "iron", 70, 6, "archer", 10, 14, 12);
        Soldiers soldier15 = new Soldiers(15, "Gaheris", 94, -3, 2, 0, 15, "swords", "silver", 95, 5, "knight", 7, 15, 9);
        Soldiers soldier16 = new Soldiers(16, "Uther", 109, 1, -2, 3, 13, "arrows", "iron", 85, 9, "archer", 6, 16, 10);
        Soldiers soldier17 = new Soldiers(17, "Owain", 108, 2, 1, -3, 20, "swords", "silver", 110, 10, "knight", 8, 17, 15);
        Soldiers soldier18 = new Soldiers(18, "Pellinore", 83, -1, 3, 1, 18, "arrows", "iron", 75, 8, "archer", 9, 18, 13);
        Soldiers soldier19 = new Soldiers(19, "Hector", 92, 3, 2, -2, 21, "swords", "silver", 105, 7, "knight", 10, 19, 12);

        soldier1.GetPosition2d(1, 2);
        soldier1.GetPosition3d(1, 2, 3);
        soldier1.Expire(100, false);
        soldier1.typesoldier("arrows");
        soldier1.powersword("iron");
        soldier1.Damage("iron", 50);
        soldier1.testdamage(10);
        soldier1.reduce(15);
        soldier1.valid(10);
        soldier1.damagebyarrow(10);
        soldier1.lossarrow(false);
        soldier1.checkthing("arrow");
        soldier1.calculateweapons(50, "arrow", 10);
        soldier1.reducehealth(); soldier1.strikeoponent();
        soldier1.attackbyarcher();
        soldier2.GetPosition2d(-1, 2);
        soldier2.GetPosition3d(-1, 2, -3);
        soldier2.Expire(90, true);
        soldier2.typesoldier("swords");
        soldier2.powersword("silver");
        soldier2.Damage("silver", 100);
        soldier2.testdamage(20);
        soldier2.reduce(25);
        soldier2.valid(5);
        soldier2.damagebyarrow(5);
        soldier2.lossarrow(false);
        soldier2.checkthing("sword");
        soldier2.calculateweapons(100, "sword", 20);

        soldier2.reducehealth();
        soldier2.strikeoponent();
        soldier2.attackbyarcher();
        soldier3.GetPosition2d(0, 0);
        soldier3.GetPosition3d(0, 0, 0);
        soldier3.Expire(110, false);
        soldier3.typesoldier("arrows");
        soldier3.powersword("iron");
        soldier3.Damage("iron", 75);
        soldier3.testdamage(8);
        soldier3.reduce(30);
        soldier3.valid(8);
        soldier3.damagebyarrow(8);
        soldier3.lossarrow(false);
        soldier3.checkthing("arrow");
        soldier3.calculateweapons(75, "arrow", 8);
        soldier3.reducehealth();
        soldier3.strikeoponent();
        soldier3.attackbyarcher();
        Soldiers soldier20 = new Soldiers(20, "Ector", 107, -3, -3, 2, 14, "arrows", "iron", 65, 6, "archer", 8, 20, 10);
        Soldiers soldier21 = new Soldiers(21, "Brastias", 91, 2, 2, 0, 13, "swords", "silver", 100, 5, "knight", 7, 21, 11);
        Soldiers soldier22 = new Soldiers(22, "Lucan", 95, -2, 1, -1, 12, "arrows", "iron", 70, 4, "archer", 6, 22, 9);
        Soldiers soldier23 = new Soldiers(23, "Palamedes", 88, 1, 3, 1, 23, "swords", "silver", 115, 7, "knight", 8, 23, 12);
        Soldiers soldier24 = new Soldiers(24, "Safir", 84, -1, -2, 2, 19, "arrows", "iron", 80, 10, "archer", 9, 24, 11);
        Soldiers soldier25 = new Soldiers(25, "Segwarides", 100, 3, 0, -3, 17, "swords", "silver", 90, 6, "knight", 10, 25, 10);
        Soldiers soldier26 = new Soldiers(26, "Ywain", 105, -3, 2, 1, 15, "arrows", "iron", 95, 5, "archer", 7, 26, 9);
        Soldiers soldier27 = new Soldiers(27, "Ban", 90, 2, -1, 3, 16, "swords", "silver", 100, 9, "knight", 8, 27, 11);
        Soldiers soldier28 = new Soldiers(28, "Bors", 97, -2, 3, -2, 11, "arrows", "iron", 70, 8, "archer", 6, 28, 8);
        Soldiers soldier29 = new Soldiers(29, "Blamor", 86, 1, -3, 2, 13, "swords", "silver", 80, 7, "knight", 5, 29, 9);
        Soldiers soldier30 = new Soldiers(30, "Galahalt", 94, -3, 1, -3, 12, "arrows", "iron", 75, 9, "archer", 7, 30, 8);
        soldier20.GetPosition2d(-3, -3); soldier20.GetPosition3d(-3, -3, 2);
        soldier20.Expire(107, false);
        soldier20.typesoldier("arrows");

        soldier20.powersword("iron");
        soldier20.Damage("iron", 65);
        soldier20.testdamage(14);
        soldier20.reduce(14);
        soldier20.valid(6);
        soldier20.damagebyarrow(6);
        soldier20.lossarrow(false);
        soldier20.checkthing("arrow");
        soldier20.calculateweapons(65, "arrow", 14);
        soldier20.reducehealth();
        soldier20.strikeoponent();
        soldier20.attackbyarcher();
        soldier21.GetPosition2d(2, 2);
        soldier21.GetPosition3d(2, 2, 0);
        soldier21.Expire(91, true);
        soldier21.typesoldier("swords");
        soldier21.powersword("silver");
        soldier21.Damage("silver", 100);
        soldier21.testdamage(13);
        soldier21.reduce(13);
        soldier21.valid(5);
        soldier21.damagebyarrow(5);
        soldier21.lossarrow(false);
        soldier21.checkthing("sword");
        soldier21.calculateweapons(100, "sword", 13);
        soldier21.reducehealth();
        soldier21.strikeoponent();
        soldier21.attackbyarcher();
        soldier22.GetPosition2d(-2, 1);
        soldier22.GetPosition3d(-2, 1, -1);
        soldier22.Expire(95, false);
        soldier22.typesoldier("arrows");
        soldier22.powersword("iron");
        soldier22.Damage("iron", 70);
        soldier22.testdamage(12);
        soldier22.reduce(12);
        soldier22.valid(4);
        soldier22.damagebyarrow(4);
        soldier22.lossarrow(false);
        soldier22.checkthing("arrow");
        soldier22.calculateweapons(70, "arrow", 12);
        soldier22.reducehealth();
        soldier22.strikeoponent();
        soldier22.attackbyarcher();
        soldier23.GetPosition2d(1, 3);
        soldier23.GetPosition3d(1, 3, 1);
        soldier23.Expire(88, true);
        soldier23.typesoldier("swords");
        soldier23.powersword("silver");
        soldier23.Damage("silver", 115);
        soldier23.testdamage(23);
        soldier23.reduce(23);
        soldier23.valid(7);
        soldier23.damagebyarrow(7);
        soldier23.lossarrow(false);
        soldier23.checkthing("sword");
        soldier23.calculateweapons(115, "sword", 23);
        soldier23.reducehealth();
        soldier23.strikeoponent();
        soldier23.attackbyarcher();
        soldier24.GetPosition2d(-1, -2);
        soldier24.GetPosition3d(-1, -2, 2);
        soldier24.Expire(84, false);
        soldier24.typesoldier("arrows");
        soldier24.powersword("iron");
        soldier24.Damage("iron", 80);
        soldier24.testdamage(19);
        soldier24.reduce(19);
        soldier24.valid(10);
        soldier24.damagebyarrow(10);
        soldier24.lossarrow(false);
        soldier24.checkthing("arrow");
        soldier24.calculateweapons(80, "arrow", 19);
        soldier24.reducehealth();
        soldier24.strikeoponent();
        soldier24.attackbyarcher();
        soldier25.GetPosition2d(3, 0);
        soldier25.GetPosition3d(3, 0, -3);
        soldier25.Expire(100, true);
        soldier25.typesoldier("swords");
        soldier25.powersword("silver");
        soldier25.Damage("silver", 90);
        soldier25.testdamage(17);
        soldier25.reduce(17);
        soldier25.valid(6);
        soldier25.damagebyarrow(6);
        soldier25.lossarrow(false);
        soldier25.checkthing("sword");
        soldier25.calculateweapons(90, "sword", 17);
        soldier25.reducehealth();
        soldier25.strikeoponent();
        soldier25.attackbyarcher();
        soldier26.GetPosition2d(-3, 2);
        soldier26.GetPosition3d(-3, 2, 1);
        soldier26.Expire(105, false);
        soldier26.typesoldier("arrows");
        soldier26.powersword("iron");
        soldier26.Damage("iron", 95);
        soldier26.testdamage(15);
        soldier26.reduce(15);
        soldier26.valid(5);
        soldier26.damagebyarrow(5);
        soldier26.lossarrow(false);
        soldier26.checkthing("arrow");
        soldier26.calculateweapons(95, "arrow", 15);
        soldier26.reducehealth();
        soldier26.strikeoponent();
        soldier26.attackbyarcher();
        soldier27.GetPosition2d(2, -1);
        soldier27.GetPosition3d(2, -1, 3);
        soldier27.Expire(90, true);
        soldier27.typesoldier("swords");
        soldier27.powersword("silver");
        soldier27.Damage("silver", 100);
        soldier27.testdamage(16);
        soldier27.reduce(16);
        soldier27.valid(9);
        soldier27.damagebyarrow(8);
        soldier28.GetPosition2d(-2, 3);
        soldier28.GetPosition3d(-2, 3, -2);
        soldier28.Expire(97, false);
        soldier28.typesoldier("arrows");
        soldier28.powersword("iron");
        soldier28.Damage("iron", 70);
        soldier28.testdamage(11);
        soldier28.reduce(11);
        soldier28.valid(8);
        soldier28.damagebyarrow(8);
        soldier28.lossarrow(false);
        soldier28.checkthing("arrow");
        soldier28.calculateweapons(70, "arrow", 11);
        soldier28.reducehealth();
        soldier28.strikeoponent();
        soldier28.attackbyarcher();
        soldier29.GetPosition2d(1, -3);
        soldier29.GetPosition3d(1, -3, 2);
        soldier29.Expire(86, true);
        soldier29.typesoldier("swords");
        soldier29.powersword("silver");
        soldier29.Damage("silver", 80);
        soldier29.testdamage(13);
        soldier29.reduce(13);
        soldier29.valid(7);
        soldier29.damagebyarrow(7);
        soldier29.lossarrow(false);
        soldier29.checkthing("sword");
        soldier29.calculateweapons(80, "sword", 13);
        soldier29.reducehealth();
        soldier29.strikeoponent();
        soldier29.attackbyarcher();
        soldier30.GetPosition2d(-3, 1);
        soldier30.GetPosition3d(-3, 1, -3);
        soldier30.Expire(94, false);
        soldier30.typesoldier("arrows");
        soldier30.powersword("iron");
        soldier30.Damage("iron", 75);
        soldier30.testdamage(12);
        soldier30.reduce(12);
        soldier30.valid(9);
        soldier30.damagebyarrow(9);
        soldier30.lossarrow(false);
        soldier30.checkthing("arrow");
        soldier30.calculateweapons(75, "arrow", 12);
        soldier30.reducehealth();
        soldier30.strikeoponent();
        soldier30.attackbyarcher();
        soldier4.GetPosition2d(2, -2);
        soldier4.GetPosition3d(2, -2, 1);
        soldier4.Expire(95, false);
        soldier4.typesoldier("arrows");
        soldier4.powersword("iron");
        soldier4.Damage("iron", 60);
        soldier4.testdamage(12);
        soldier4.reduce(12);
        soldier4.valid(9);
        soldier4.damagebyarrow(9);
        soldier4.lossarrow(false);
        soldier4.checkthing("arrow");
        soldier4.calculateweapons(60, "arrow", 12);
        soldier4.reducehealth();
        soldier4.strikeoponent();
        soldier4.attackbyarcher();
        soldier5.GetPosition2d(-2, 3);
        soldier5.GetPosition3d(-2, 3, -1);
        soldier5.Expire(105, true);
        soldier5.typesoldier("swords");
        soldier5.powersword("silver");
        soldier5.Damage("silver", 120);
        soldier5.testdamage(18);
        soldier5.reduce(18);
        soldier5.valid(4);
        soldier5.damagebyarrow(4);
        soldier5.lossarrow(false);
        soldier5.checkthing("sword");
        soldier5.calculateweapons(120, "sword", 18);
        soldier5.reducehealth();
        soldier5.strikeoponent();
        soldier5.attackbyarcher();
        soldier6.GetPosition2d(1, 3);
        soldier6.GetPosition3d(1, 3, 1);
        soldier6.Expire(98, false);
        soldier6.typesoldier("arrows");
        soldier6.powersword("iron");
        soldier6.Damage("iron", 80);
        soldier6.testdamage(25);
        soldier6.reduce(25);
        soldier6.valid(10);
        soldier6.damagebyarrow(10);
        soldier6.lossarrow(false);
        soldier6.checkthing("arrow");
        soldier6.calculateweapons(80, "arrow", 25);
        soldier6.reducehealth();
        soldier6.strikeoponent();
        soldier6.attackbyarcher();
        soldier7.GetPosition2d(-3, -2);
        soldier7.GetPosition3d(-3, -2, 2);
        soldier7.Expire(87, true);
        soldier7.typesoldier("swords");
        soldier7.powersword("silver");
        soldier7.Damage("silver", 90);
        soldier7.testdamage(30);
        soldier7.reduce(30);
        soldier7.valid(3);
        soldier7.damagebyarrow(3);
        soldier7.lossarrow(false);
        soldier7.checkthing("sword");
        soldier7.calculateweapons(90, "sword", 30);
        soldier7.reducehealth();
        soldier7.strikeoponent();
        soldier7.attackbyarcher();
        soldier8.GetPosition2d(2, 2);
        soldier8.GetPosition3d(2, 2, -2);
        soldier8.Expire(93, false);
        soldier8.typesoldier("arrows");
        soldier8.powersword("iron");
        soldier8.Damage("iron", 55);
        soldier8.testdamage(14);
        soldier8.reduce(14);
        soldier8.valid(7);
        soldier8.damagebyarrow(7);
        soldier8.lossarrow(false);
        soldier8.checkthing("arrow");
        soldier8.calculateweapons(55, "arrow", 14);
        soldier8.reducehealth();
        soldier8.strikeoponent();
        soldier8.attackbyarcher();
        soldier9.GetPosition2d(0, 2);
        soldier9.GetPosition3d(0, 2, 3);
        soldier9.Expire(110, true);
        soldier9.typesoldier("swords");
        soldier9.powersword("silver");
        soldier9.Damage("silver", 110);
        soldier9.testdamage(10);
        soldier9.reduce(10);
        soldier9.valid(6);
        soldier9.damagebyarrow(6);
        soldier9.lossarrow(false);
        soldier9.checkthing("sword");
        soldier9.calculateweapons(110, "archer", 55);
        soldier10.GetPosition2d(-1, 1); 
        soldier10.GetPosition3d(-1, 1, 2); 
        soldier10.Expire(99, false); 
        soldier10.typesoldier("arrows"); 
        soldier10.powersword("iron"); 
        soldier10.Damage("iron", 95); 
        soldier10.testdamage(22); 
        soldier10.reduce(22);
        soldier10.valid(9);
        soldier10.damagebyarrow(9);
        soldier10.lossarrow(false); 
        soldier10.checkthing("arrow"); 
        soldier10.calculateweapons(95, "arrow", 22); 
        soldier10.reducehealth(); 
        soldier10.strikeoponent(); 
        soldier10.attackbyarcher();
        soldier11.GetPosition2d(1, -3);
        soldier11.GetPosition3d(1, -3, -2);
        soldier11.Expire(85, true);
        soldier11.typesoldier("swords"); 
        soldier11.powersword("silver"); 
        soldier11.Damage("silver", 85); 
        soldier11.testdamage(16);
        soldier11.reduce(16); 
        soldier11.valid(8); 
        soldier11.damagebyarrow(8);
        soldier11.lossarrow(false); 
        soldier11.checkthing("sword"); 
        soldier11.calculateweapons(85, "sword", 16); 
        soldier11.reducehealth(); 
        soldier11.strikeoponent(); 
        soldier11.attackbyarcher(); 
        soldier12.GetPosition2d(3, 0);
        soldier12.GetPosition3d(3, 0, 3); 
        soldier12.Expire(101, false); 
        soldier12.typesoldier("arrows"); 
        soldier12.powersword("iron"); 
        soldier12.Damage("iron", 60); 
        soldier12.testdamage(10); 
        soldier12.reduce(10); 
        soldier12.valid(4); 
        soldier12.damagebyarrow(4); 
        soldier12.lossarrow(false);
        soldier12.checkthing("arrow"); 
        soldier12.calculateweapons(60, "arrow", 10); 
        soldier12.reducehealth();
        soldier12.strikeoponent(); 
        soldier12.attackbyarcher(); 
        soldier13.GetPosition2d(-2, -1); 
        soldier13.GetPosition3d(-2, -1, 1); 
        soldier13.Expire(96, true);
        soldier13.typesoldier("swords");
        soldier13.powersword("silver"); 
        soldier13.Damage("silver", 105); 
        soldier13.testdamage(19);
        soldier13.reduce(19); 
        soldier13.valid(7); 
        soldier13.damagebyarrow(7); 
        soldier13.lossarrow(false); 
        soldier13.checkthing("sword"); 
        soldier13.calculateweapons(105, "sword", 19); 
        soldier13.reducehealth(); 
        soldier13.strikeoponent(); 
        soldier13.attackbyarcher(); 
        soldier14.GetPosition2d(0, 3); 
        soldier14.GetPosition3d(0, 3, -1); 
        soldier14.Expire(89, false); 
        soldier14.typesoldier("arrows"); 
        soldier14.powersword("iron"); 
        soldier14.Damage("iron", 70); 
        soldier14.testdamage(27); 
        soldier14.reduce(27); 
        soldier14.valid(6); 
        soldier14.damagebyarrow(6); 
        soldier14.lossarrow(false); 
        soldier14.checkthing("arrow"); 
        soldier14.calculateweapons(70, "arrow", 27);
        soldier14.reducehealth(); 
        soldier14.strikeoponent();
        soldier14.attackbyarcher();
        soldier15.GetPosition2d(-3, 2);
        soldier15.GetPosition3d(-3, 2, 0);
        soldier15.Expire(94, true); 
        soldier15.typesoldier("swords");
        soldier15.powersword("silver"); 
        soldier15.Damage("silver", 95); 
        soldier15.testdamage(15); 
        soldier15.reduce(15);
        soldier15.valid(5); 
        soldier15.damagebyarrow(5); 
        soldier15.lossarrow(false);
        soldier15.checkthing("sword"); 
        soldier15.calculateweapons(95, "sword", 15);
        soldier15.reducehealth(); 
        soldier15.strikeoponent();
        soldier15.attackbyarcher();
        soldier16.GetPosition2d(1, -2); 
        soldier16.GetPosition3d(1, -2, 3); 
        soldier16.Expire(109, false); 
        soldier16.typesoldier("arrows");
        soldier16.powersword("iron");
        soldier16.Damage("iron", 85); 
        soldier16.testdamage(13); 
        soldier16.reduce(13); 
        soldier16.valid(9);
        soldier16.damagebyarrow(9); 
        soldier16.lossarrow(false); 
        soldier16.checkthing("arrow");
        soldier16.calculateweapons(85, "arrow", 13);
        soldier16.reducehealth(); 
        soldier16.strikeoponent(); 
        soldier16.attackbyarcher();
        soldier17.GetPosition2d(2, 1);
        soldier17.GetPosition3d(2, 1, -3); 
        soldier17.Expire(108, true); 
        soldier17.typesoldier("swords"); 
        soldier17.powersword("silver"); 
        soldier17.Damage("silver", 110); 
        soldier17.testdamage(20); 
        soldier17.reduce(20); 
        soldier17.valid(10); 
        soldier17.damagebyarrow(10); 
        soldier17.lossarrow(false); 
        soldier17.checkthing("sword"); 
        soldier17.calculateweapons(110, "sword", 20);
        soldier17.reducehealth();
        soldier17.strikeoponent(); 
        soldier17.attackbyarcher();
        soldier18.GetPosition2d(-1, 3);
        soldier18.GetPosition3d(-1, 3, 1); 
        soldier18.Expire(83, false); 
        soldier18.typesoldier("arrows");
        soldier18.powersword("iron");
        soldier18.Damage("iron", 75);
        soldier18.testdamage(18); 
        soldier18.reduce(18); 
        soldier18.valid(8); 
        soldier18.damagebyarrow(8);
        soldier18.lossarrow(false); 
        soldier18.checkthing("arrow");
        soldier18.calculateweapons(75, "arrow", 18); 
        soldier18.reducehealth(); 
        soldier18.strikeoponent();
        soldier18.attackbyarcher(); 
        soldier19.GetPosition2d(3, 2);
        soldier19.GetPosition3d(3, 2, -2);
        soldier19.Expire(92, true);
        soldier19.typesoldier("swords"); 
        soldier19.powersword("silver"); 
        soldier19.Damage("silver", 105); 
        soldier19.testdamage(21); 
        soldier19.reduce(21); 
        soldier19.valid(7); 
        soldier19.damagebyarrow(7);
        soldier19.lossarrow(false); 
        soldier19.checkthing("sword"); 
        soldier19.calculateweapons(105, "sword", 21); 
        soldier19.reducehealth();
        soldier19.strikeoponent(); 
        soldier19.attackbyarcher();
        
          Utility utility1 = new Utility();
        Utility utility2 = new Utility();
        Utility utility3 = new Utility(); 
        Utility utility4 = new Utility(); 
        Utility utility5 = new Utility(); 
        Utility utility6 = new Utility(); 
        Utility utility7 = new Utility();
        Utility utility8 = new Utility(); 
        Utility utility9 = new Utility(); 
        Utility utility10 = new Utility(); 
        Utility utility11 = new Utility();
        Utility utility12 = new Utility(); 
        Utility utility13 = new Utility(); 
        Utility utility14 = new Utility(); 
        Utility utility15 = new Utility(); 
        Utility utility16 = new Utility(); 
        Utility utility17 = new Utility(); 
        Utility utility18 = new Utility(); 
        Utility utility19 = new Utility(); 
        Utility utility20 = new Utility(); 
        utility1.producenumber();
        utility2.producenumber(); 
        utility3.producenumber(); 
        utility4.producenumber(); 
        utility5.producenumber();
        utility6.producenumber(); 
        utility7.producenumber();
        utility8.producenumber();
        utility9.producenumber(); 
        utility10.producenumber();
        utility11.producenumber(); 
        utility12.producenumber();
        utility13.producenumber(); 
        utility14.producenumber(); 
        utility15.producenumber(); 
        utility16.producenumber();
        utility17.producenumber();
        utility18.producenumber();
        utility19.producenumber(); 
        utility20.producenumber(); 
        Console.WriteLine(utility1.GetRandomPosition2D(10, 20));
        Console.WriteLine(utility2.GetRandomPosition2D(10, 20));
        Console.WriteLine(utility3.GetRandomPosition2D(10, 20));
        Console.WriteLine(utility4.GetRandomPosition2D(10, 20));
        Console.WriteLine(utility5.GetRandomPosition2D(10, 20));
        Console.WriteLine(utility6.GetRandomPosition2D(10, 20)); 
        Console.WriteLine(utility7.GetRandomPosition2D(10, 20)); 
        Console.WriteLine(utility8.GetRandomPosition2D(10, 20)); 
        Console.WriteLine(utility9.GetRandomPosition2D(10, 20));
        Console.WriteLine(utility10.GetRandomPosition2D(10, 20)) ;
        Console.WriteLine(utility11.GetRandomPosition2D(10, 20));
        Console.WriteLine(utility12.GetRandomPosition2D(10, 20)); 
        Console.WriteLine(utility13.GetRandomPosition2D(10, 20));
        Console.WriteLine(utility14.GetRandomPosition2D(10, 20));
        Console.WriteLine(utility15.GetRandomPosition2D(10, 20)); 
        Console.WriteLine(utility16.GetRandomPosition2D(10, 20));
        Console.WriteLine(utility17.GetRandomPosition2D(10, 20));
        Console.WriteLine(utility18.GetRandomPosition2D(10, 20)); 
        Console.WriteLine(utility19.GetRandomPosition2D(10, 20));
        Console.WriteLine(utility20.GetRandomPosition2D(10, 20));
        Console.WriteLine(utility1.GetRandomPosition3D(10, 20, 30));
        Console.WriteLine(utility2.GetRandomPosition3D(10, 20, 30));
        Console.WriteLine(utility3.GetRandomPosition3D(10, 20, 30));
        Console.WriteLine(utility4.GetRandomPosition3D(10, 20, 30)); 
        Console.WriteLine(utility5.GetRandomPosition3D(10, 20, 30)); 
        Console.WriteLine(utility6.GetRandomPosition3D(10, 20, 30));
        Console.WriteLine(utility7.GetRandomPosition3D(10, 20, 30)); 
        Console.WriteLine(utility8.GetRandomPosition3D(10, 20, 30)); 
        Console.WriteLine(utility9.GetRandomPosition3D(10, 20, 30)); 
        Console.WriteLine(utility10.GetRandomPosition3D(10, 20, 30)); 
        Console.WriteLine(utility11.GetRandomPosition3D(10, 20, 30)); 
        Console.WriteLine(utility12.GetRandomPosition3D(10, 20, 30)); 
        Console.WriteLine(utility13.GetRandomPosition3D(10, 20, 30)); 
        Console.WriteLine(utility14.GetRandomPosition3D(10, 20, 30)); 
        Console.WriteLine(utility15.GetRandomPosition3D(10, 20, 30)); 
        Console.WriteLine(utility16.GetRandomPosition3D(10, 20, 30)); 
        Console.WriteLine(utility17.GetRandomPosition3D(10, 20, 30)); 
        Console.WriteLine(utility18.GetRandomPosition3D(10, 20, 30));
        Console.WriteLine(utility19.GetRandomPosition3D(10, 20, 30));
        Console.WriteLine(utility20.GetRandomPosition3D(10, 20, 30));
         Console.WriteLine(utility1.GetRandomAction()); 
        Console.WriteLine(utility2.GetRandomAction());
        Console.WriteLine(utility3.GetRandomAction());
        Console.WriteLine(utility4.GetRandomAction());
        Console.WriteLine(utility5.GetRandomAction());
        Console.WriteLine(utility6.GetRandomAction());
        Console.WriteLine(utility7.GetRandomAction());
        Console.WriteLine(utility8.GetRandomAction());
        Console.WriteLine(utility9.GetRandomAction());
        Console.WriteLine(utility10.GetRandomAction());
        Console.WriteLine(utility11.GetRandomAction());
        Console.WriteLine(utility12.GetRandomAction()); 
        Console.WriteLine(utility13.GetRandomAction()); 
        Console.WriteLine(utility14.GetRandomAction());
        Console.WriteLine(utility15.GetRandomAction());
        Console.WriteLine(utility16.GetRandomAction()); 
        Console.WriteLine(utility17.GetRandomAction()); 
        Console.WriteLine(utility18.GetRandomAction());
        Console.WriteLine(utility19.GetRandomAction());
        Console.WriteLine(utility20.GetRandomAction());
        Console.WriteLine(utility1.CalculateScore(1, 2, 3, 4));
        Console.WriteLine(utility2.CalculateScore(1, 2, 3, 4)) ; 
        Console.WriteLine(utility3.CalculateScore(1, 2, 3, 4)); 
        Console.WriteLine(utility4.CalculateScore(1, 2, 3, 4)); 
        Console.WriteLine(utility5.CalculateScore(1, 2, 3, 4));
        Console.WriteLine(utility6.CalculateScore(1, 2, 3, 4)); 
        Console.WriteLine(utility7.CalculateScore(1, 2, 3, 4));
        Console.WriteLine(utility8.CalculateScore(1, 2, 3, 4)); 
        Console.WriteLine(utility9.CalculateScore(1, 2, 3, 4));
        Console.WriteLine(utility10.CalculateScore(1, 2, 3, 4));
        Console.WriteLine(utility11.CalculateScore(1, 2, 3, 4));
        Console.WriteLine(utility12.CalculateScore(5,6,6,6));

        }
}
